### ISSUE TITLE
Add Perplexity provider

### ISSUE THREAD

**Issue by samuelrince** [genai-impact/ecologits#25]
## Description

Add [perplexity.ai](https://perplexity.ai) LLM provider.

## Solution

Perplexity uses the same API as OpenAI, meaning the OpenAI python client is compatible with their service, and it only requires changing the API endpoint.

Client example: https://docs.perplexity.ai/docs/getting-started
Supported models: https://docs.perplexity.ai/docs/model-cards

We need to identify when another provider is used in the case of the OpenAI client. Plus support and register the models that they provide through their API.

**Comment by LucBERTON** [comment]
I created `feat/add-perplexity-provider` branch  to work on this topic.
Anyone has an api key in order to test the code and record a vcr?

### Regarding openai tracer
In the models data file, I added perplexity models as provided by `openai` in order to leverage the openai tracer in its current state.
We'll probably need to update the tracer so it can work with dynamic `provider` values.

### Regarding models data
I flagged the perplexity models with _model_architecture_not_released_ but not the open source ones.
I am also not completely sure what `8x7B` means as parameter count I indicated only `7` in the file.

**Comment by adrienbanse** [comment]
@samuelrince @LucBERTON  Quick question here: why do we need to modify the tracer for another endpoint? I think that adding the supported models for the OpenAI provider would be enough

**Comment by samuelrince** [comment]
Yes we can keep the OpenAI tracer, we just need to detect the right provider (looking at the endpoint). Let's not mix Perplexity models with OpenAI.

PS: I would not implement it for now unless it is asked by one of our users :)
